add missing typename for llvm/15.0.7 (#3128)
detected during nightly Trilinos integration testing with llvm/15.0.7
with deprecated code off; resolves error of type:

18:23:20 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Nrm.hpp:17:27: error: missing 'typename' prior to dependent type name 'Kokkos::TeamPolicy<execution_space>::member_type'

Signed-off-by: Nathan Ellingwood <ndellin@sandia.gov>