Remove bash error from cm_generate_makefile
Line 583 was doing $(ls $KOKKOS_PATH), which was trying to interpret
the results of the ls as a command. It said something like
error: command "algorithms" not found. This line can be removed since
the check for existence of $KOKKOS_PATH/CMakeLists.txt also implies that
$KOKKOS_PATH exists.